#admin-repo
spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample_admin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: data
    password: datapwd
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 30000
      minimum-idle: 3
      maximum-pool-size: 10
      validation-timeout: 20000
      connection-timeout: 30000
      connection-test-query: "select 1"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tnxsample
      username: data
      password: datapwd

